# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 231b694e3859c565d204b4c80536f2926099baf8dea4c1e7781e665edcc34dede397f30d5d652e5d94b0593d5fd534a73f63f8b3b95c53333ee901fcc5189484

test:
  secret_key_base: aca56b22e2234cd3425baf944cd3a4d06bd972038e3e78b8c27d1a3db11bc8597f2d0a5409cf658c1510ddeca951469fcf4078e21f904c90f1f572fad57723b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
